In [21]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [22]:
file_path = "/home/min/7cmdehdrb/project_th/rtde_log.csv"

data = pd.read_csv(file_path)

# display(data.keys())

R_elbow = data["R_elbow_p"].values
S_elbow = data["S_elbow_p"].values

# R_elbow = data["R_shoulder_lift_p"].values
# S_elbow = data["S_shoulder_lift_p"].values

d_elbow = R_elbow - S_elbow

abs_d_elbow = np.abs(d_elbow)

d_elbow_max = np.rad2deg(abs_d_elbow.max())
d_elbow_min = np.rad2deg(abs_d_elbow.min())
d_elbow_mean = np.rad2deg(abs_d_elbow.mean())
d_elbow_std = np.rad2deg(abs_d_elbow.std())

display(d_elbow_max)
display(d_elbow_min)
display(d_elbow_mean)
display(d_elbow_std)

df = pd.DataFrame(
    {
        "d_elbow": d_elbow,
    }
)

display(df)

1.3778155114666162

2.8705654218614904e-05

0.2207328552926128

0.26230152199765616

      d_elbow
0   -0.007567
1   -0.022534
2   -0.024047
3   -0.018563
4   -0.014535
..        ...
115  0.000148
116  0.000086
117  0.000049
118  0.000027
119  0.000169

[120 rows x 1 columns]

In [23]:
file_path = "/home/min/7cmdehdrb/project_th/rtde_log.csv"

data = pd.read_csv(file_path)

# display(data.keys())

R_elbow = data["R_elbow_p"].values
S_elbow = data["S_elbow_p"].values

# R_elbow = data["R_shoulder_lift_p"].values
# S_elbow = data["S_shoulder_lift_p"].values

d_elbow = R_elbow - S_elbow

abs_d_elbow = np.abs(d_elbow)

d_elbow_max = np.rad2deg(abs_d_elbow.max())
d_elbow_min = np.rad2deg(abs_d_elbow.min())
d_elbow_mean = np.rad2deg(abs_d_elbow.mean())
d_elbow_std = np.rad2deg(abs_d_elbow.std())

display(d_elbow_max)
display(d_elbow_min)
display(d_elbow_mean)
display(d_elbow_std)

df = pd.DataFrame(
    {
        "d_elbow": d_elbow,
    }
)

display(df)

1.7567429240586354

0.005636588921181864

0.4038291776923337

0.4050168844894387

      d_elbow
0   -0.000718
1    0.005967
2    0.007956
3    0.005931
4    0.004764
..        ...
115 -0.000956
116 -0.000846
117 -0.000778
118 -0.000738
119 -0.000682

[120 rows x 1 columns]

In [29]:
file_path = "/home/min/7cmdehdrb/project_th/rtde_log.csv"

data = pd.read_csv(file_path)

# display(data)

R_elbow = data["R_elbow_p"].values[:-2]
S_elbow = data["S_elbow_p"].values[:-2]

# R_elbow = data["R_shoulder_lift_p"].values
# S_elbow = data["S_shoulder_lift_p"].values

d_elbow = R_elbow - S_elbow

abs_d_elbow = np.abs(d_elbow)

d_elbow_max = np.rad2deg(abs_d_elbow.max())
d_elbow_min = np.rad2deg(abs_d_elbow.min())
d_elbow_mean = np.rad2deg(abs_d_elbow.mean())
d_elbow_std = np.rad2deg(abs_d_elbow.std())

display(d_elbow_max)
display(d_elbow_min)
display(d_elbow_mean)
display(d_elbow_std)

df = pd.DataFrame(
    {
        "d_elbow": d_elbow,
    }
)

display(df)

2.51068051922269

0.0032648855152312877

0.5298166843677008

0.6102690511054925

     d_elbow
0   0.000057
1  -0.042752
2  -0.043820
3  -0.037046
4  -0.028839
5  -0.021460
6  -0.017524
7  -0.011301
8  -0.011293
9  -0.009591
10 -0.006946
11 -0.005136
12 -0.004970
13 -0.004340
14 -0.003813
15 -0.006200
16 -0.006359
17 -0.006364
18 -0.004524
19 -0.003471
20 -0.003835
21 -0.006370
22 -0.006069
23 -0.006271
24 -0.006119
25 -0.005728
26 -0.004357
27 -0.003662
28 -0.005085
29 -0.005013
30 -0.004665
31 -0.004642
32 -0.004612
33 -0.003201
34 -0.003014
35 -0.002701
36 -0.002160
37 -0.003777
38 -0.003548

In [30]:
file_path = "/home/min/7cmdehdrb/project_th/rtde_log.csv"

data = pd.read_csv(file_path)

# display(data)

R_elbow = data["R_shoulder_lift_p"].values
S_elbow = data["S_shoulder_lift_p"].values


d_elbow = R_elbow - S_elbow

abs_d_elbow = np.abs(d_elbow)

d_elbow_max = np.rad2deg(abs_d_elbow.max())
d_elbow_min = np.rad2deg(abs_d_elbow.min())
d_elbow_mean = np.rad2deg(abs_d_elbow.mean())
d_elbow_std = np.rad2deg(abs_d_elbow.std())

display(d_elbow_max)
display(d_elbow_min)
display(d_elbow_mean)
display(d_elbow_std)

df = pd.DataFrame(
    {
        "d_elbow": d_elbow,
    }
)

display(df)

0.02519105237856071

7.750230894385636e-05

0.006992330445967338

0.005517236438836335

     d_elbow
0  -0.000440
1  -0.000302
2  -0.000036
3   0.000049
4  -0.000097
5  -0.000272
6  -0.000004
7  -0.000096
8  -0.000247
9  -0.000102
10  0.000041
11 -0.000046
12 -0.000133
13  0.000016
14 -0.000231
15 -0.000114
16  0.000001
17 -0.000033
18 -0.000074
19 -0.000183
20 -0.000114
21 -0.000167
22 -0.000189
23  0.000062
24 -0.000169
25 -0.000254
26  0.000029
27 -0.000242
28 -0.000125
29 -0.000031
30 -0.000004
31 -0.000160
32 -0.000053
33 -0.000072
34 -0.000060
35 -0.000162
36 -0.000014
37 -0.000176
38 -0.000176
39 -0.000264
40  0.000061
41 -0.000180
42  0.000096
43 -0.000102
44  0.000033
45 -0.000277
46 -0.000264
47 -0.000003
48 -0.000163
49 -0.000163
50  0.000031
51 -0.000017
52 -0.000148
53  0.000012

In [31]:
file_path = "/home/min/7cmdehdrb/project_th/rtde_log.csv"

data = pd.read_csv(file_path)

# display(data)

R_elbow = data["R_elbow_p"].values
S_elbow = data["S_elbow_p"].values


d_elbow = R_elbow - S_elbow

abs_d_elbow = np.abs(d_elbow)

d_elbow_max = np.rad2deg(abs_d_elbow.max())
d_elbow_min = np.rad2deg(abs_d_elbow.min())
d_elbow_mean = np.rad2deg(abs_d_elbow.mean())
d_elbow_std = np.rad2deg(abs_d_elbow.std())

display(d_elbow_max)
display(d_elbow_min)
display(d_elbow_mean)
display(d_elbow_std)

df = pd.DataFrame(
    {
        "d_elbow": d_elbow,
    }
)

display(df)

3.628141981305562

0.45230019770303254

1.8941090094602406

0.8079084463848287

     d_elbow
0   0.013092
1   0.030237
2   0.035990
3   0.040341
4   0.045872
5   0.034142
6   0.014697
7   0.022989
8   0.023636
9   0.021573
10  0.037483
11  0.033825
12  0.032719
13  0.041422
14  0.010163
15  0.007894
16  0.033823
17  0.029468
18  0.055638
19  0.043296
20  0.052894
21  0.063323
22  0.046485
23 -0.022399

In [32]:
file_path = "/home/min/7cmdehdrb/project_th/rtde_log.csv"

data = pd.read_csv(file_path)

# display(data)

R_elbow = data["R_elbow_p"].values
S_elbow = data["S_elbow_p"].values


d_elbow = R_elbow - S_elbow

abs_d_elbow = np.abs(d_elbow)

d_elbow_max = np.rad2deg(abs_d_elbow.max())
d_elbow_min = np.rad2deg(abs_d_elbow.min())
d_elbow_mean = np.rad2deg(abs_d_elbow.mean())
d_elbow_std = np.rad2deg(abs_d_elbow.std())

display(d_elbow_max)
display(d_elbow_min)
display(d_elbow_mean)
display(d_elbow_std)

df = pd.DataFrame(
    {
        "d_elbow": d_elbow,
    }
)

display(df)

4.48528511078715

0.03562276113835062

2.08915431068295

1.315854848474216

     d_elbow
0   0.000622
1   0.034546
2  -0.033322
3  -0.056027
4   0.000757
5   0.021028
6   0.022533
7   0.042829
8   0.055821
9   0.074921
10  0.043564
11  0.077002
12  0.061478
13  0.017548
14 -0.000754
15  0.028283
16  0.047774
17  0.026069
18  0.078283
19  0.023942
20  0.028195
21  0.026881